name: Export my notion workspace

on:
  schedule:
    - cron: "0 */6 * * *" # Call the export every 6 hours
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          tokne: ${{ secrets.GITHUB_TOKEN }}

      - uses: 0x7d4/notionweb@v0.0.1-alpha.4
        with:
          page: 7a464aba4a42409da5b03163637a2120
          token-v2: ${{ secrets.NOTION_TOKEN_V2 }}
          file-token: ${{ secrets.NOTION_FILE_TOKEN }}

      - name: Push changes
        run: |
          ls -al
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update Notion workspace"
          git push
