name: Export my notion workspace

on:
  schedule:
    - cron: "0 */6 * * *" # Call the export every 6 hours
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: 0x7d4/notionweb@v0.0.1-alpha.4
        with:
          page: 7a464aba4a42409da5b03163637a2120
          token-v2: ${{ secrets.NOTION_TOKEN_V2 }}
          file-token: ${{ secrets.NOTION_FILE_TOKEN }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
