name: Export my notion workspace

on:
  schedule:
    - cron: "0 */6 * * *"  # Call the export every 6 hours

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: 0x7d4/notionweb@v0.0.1-alpha.2
        with:
          page: 7a464aba4a42409da5b03163637a2120 
          token-v2: ${{ secrets.NOTION_TOKEN_V2 }}
          file-token: ${{ secrets.NOTION_FILE_TOKEN }}
